"""Cria a tabela minha_vida

Revision ID: 0aa554babb04
Revises: 
Create Date: 2025-06-22 14:10:05.219195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aa554babb04'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('minha_vida',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('nota_humor', sa.Float(), nullable=True),
    sa.Column('secreto', sa.Boolean(), nullable=True),
    sa.Column('Estudar', sa.Boolean(), nullable=True),
    sa.Column('Leitura', sa.Boolean(), nullable=True),
    sa.Column('Exercício_aerobico', sa.Boolean(), nullable=True),
    sa.Column('Alimentação_saudavel', sa.Boolean(), nullable=True),
    sa.Column('Consumo_de_agua', sa.Boolean(), nullable=True),
    sa.Column('Atencao_plena', sa.Boolean(), nullable=True),
    sa.Column('Diario_e_fixacao', sa.Boolean(), nullable=True),
    sa.Column('Academia', sa.Boolean(), nullable=True),
    sa.Column('Atividade_sexual', sa.Boolean(), nullable=True),
    sa.Column('Hora_que_eu_acordei', sa.Time(), nullable=True),
    sa.Column('Horario_que_eu_fui_dormir', sa.Time(), nullable=True),
    sa.Column('Nota_humor_fim_dia', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('minha_vida')
    # ### end Alembic commands ###
