"""Altera colunas de sono para DateTime

Revision ID: 341eea223d28
Revises: 0aa554babb04
Create Date: 2025-06-22 16:04:06.402380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '341eea223d28'
down_revision: Union[str, Sequence[str], None] = '0aa554babb04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('minha_vida', 'Horario_que_eu_fui_dormir')
    op.drop_column('minha_vida', 'Hora_que_eu_acordei')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('minha_vida', sa.Column('Hora_que_eu_acordei', sa.TIME(), nullable=True))
    op.add_column('minha_vida', sa.Column('Horario_que_eu_fui_dormir', sa.TIME(), nullable=True))
    # ### end Alembic commands ###
