"""Adiciona suporte multi-usuario com user_phone_number

Revision ID: 9b53d5511a9b
Revises: aa305788aab6
Create Date: 2025-07-24 10:48:40.603320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b53d5511a9b'
down_revision: Union[str, Sequence[str], None] = 'aa305788aab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('minha_vida', sa.Column('user_phone_number', sa.String(), nullable=False))
    op.create_unique_constraint('_user_date_uc', 'minha_vida', ['user_phone_number', 'data'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_date_uc', 'minha_vida', type_='unique')
    op.drop_column('minha_vida', 'user_phone_number')
    # ### end Alembic commands ###
