"""Adiciona status_conversa a minha_vida

Revision ID: aa305788aab6
Revises: 341eea223d28
Create Date: 2025-07-20 19:22:15.395074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa305788aab6'
down_revision: Union[str, Sequence[str], None] = '341eea223d28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('minha_vida', sa.Column('status_conversa', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('minha_vida', 'status_conversa')
    # ### end Alembic commands ###
